---
# Example MCPServer: Simple Calculator
#
# This MCP server provides basic arithmetic operations (add, subtract, multiply, divide).
# Built with FastMCP framework (https://github.com/jlowin/fastmcp)
#
# This is a minimal example demonstrating MCP server deployment without external dependencies.
#
# Prerequisites:
# 1. Build and push Docker image to ECR:
#    docker build -t mcp-calculator:1.0.0 .
#    docker tag mcp-calculator:1.0.0 ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/mcp-calculator:1.0.0
#    docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/mcp-calculator:1.0.0
#
# 2. Apply this manifest:
#    kubectl apply -f calculator.yaml
#
# 3. Test the MCP server:
#    kubectl port-forward -n litellm svc/mcp-calculator 8080:8080
#    curl http://localhost:8080/health
#
apiVersion: mcp.litellm.ai/v1alpha1
kind: MCPServer
metadata:
  name: calculator
  namespace: litellm
  labels:
    app.kubernetes.io/name: mcp-calculator
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/part-of: litellm-stack
    mcp.litellm.ai/category: utilities
spec:
  # ============================================================================
  # Server Type
  # ============================================================================
  type: internal-api

  # ============================================================================
  # MCP Transport (per MCP spec)
  # ============================================================================
  transport:
    type: http
    http:
      path: /mcp
      port: 8080
      sse: true  # Enable Server-Sent Events for streaming
      sessionManagement: true
      protocolVersion: "2025-11-25"
      originValidation: true
      allowedOrigins:
        - http://litellm-proxy.litellm.svc.cluster.local:4000

  # ============================================================================
  # Container Image
  # ============================================================================
  image:
    repository: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/mcp-calculator
    tag: "1.0.0"
    pullPolicy: IfNotPresent

  # ============================================================================
  # High Availability
  # ============================================================================
  replicas: 2

  podDisruptionBudget:
    minAvailable: 1

  affinity:
    podAntiAffinity: preferred

  # ============================================================================
  # Resources (minimal for simple calculator)
  # ============================================================================
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  # ============================================================================
  # Configuration
  # ============================================================================
  config:
    LOG_LEVEL: "info"
    MAX_PRECISION: "10"  # Maximum decimal places for results

  # ============================================================================
  # Observability
  # ============================================================================
  observability:
    metrics:
      enabled: true
      port: 8080
      path: /metrics
      interval: 30s

    tracing:
      enabled: true
      jaegerEndpoint: http://jaeger-all-in-one.monitoring.svc.cluster.local:4318
      samplingRate: 1.0

    healthProbes:
      liveness:
        path: /health
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3

      readiness:
        path: /ready
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 3

  # ============================================================================
  # LiteLLM Integration
  # ============================================================================
  litellm:
    autoRegister: true
    allowedUserGroups:
      - litellm-developers
      - litellm-admins
